//using gAPI.Core.Attributes;
//using gAPI.Core.Dtos;
//using gAPI.Core.Ids;
//using gAPI.Core.Interfaces;
//using gAPI.Core.Serializers;
//using gAPI.Core.Server.Collections;
//using gAPI.Core.Server.Fabric;
//using gAPI.Core.Server.Wss;
//using LanCloud.Shared.Interfaces;
//using Microsoft.CodeAnalysis;
//using Microsoft.Extensions.Logging;
//using System.Buffers.Binary;
//using System.Collections.Generic;
//using System.Runtime.CompilerServices;
//using System.Text;
//using System.Threading;
//using System.Threading.Tasks;

//// <auto-generated />
//#nullable enable

//namespace gAPI.Generated;

//public class ServerConnection : WssServerConnection
//{
//    readonly ILogger ___logger;
//    readonly IServerAuthenticationService ___authenticationService;
//    readonly ITestApi TestApi;
//    readonly byte[] ___Buffer = new byte[10 * 1024 * 1024];
//    readonly FabricClient ___fabricClient;

//    public ServerConnection(
//        IServerAuthenticationService authenticationService,
//        ServiceSubscriptionCollection serviceSubscriptions,
//        ServerConnectionCollection connections,
//        StreamingCache requestCache,
//        FabricClient fabricClient,
//        ITestApi testApi,
//        ILoggerFactory loggerFactory)
//        : base(authenticationService, serviceSubscriptions, connections, requestCache, fabricClient, loggerFactory)
//    {
//        this.___fabricClient = fabricClient;
//        this.___authenticationService = authenticationService;
//        this.TestApi = testApi;
//        this.___logger = loggerFactory.CreateLogger<ServerConnection>();
//    }

//    protected override Task Send_SendRequest_ToServiceAsync(SendRequestDto ___sendRequest, CancellationToken ___ct)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(___sendRequest.BinaryData);
//        switch (___sendRequest.Routing.ServiceId.Value)
//        {
//            case "ITestApi":
//                switch (___sendRequest.Routing.MethodId.Value)
//                {
//                    case "Test1":
//                        return ITestApi_Test1(
//                            ___sendRequest,
//                            ___ct);
//                    case "Test4":
//                        return ITestApi_Test4(
//                            ___sendRequest,
//                            PrimitivesSpanSerializer.ReadString(___span, ref ___offset),
//                            RegisterRemoteAsyncEnumerableArgument<string>(___sendRequest.Routing, 1, ITestApi_Test4_1_Deserializer),
//                            RegisterRemoteAsyncEnumerableArgument<string>(___sendRequest.Routing, 2, ITestApi_Test4_2_Deserializer),
//                            ___ct);
//                }
//                break;
//        }
//        throw new Exception($"Send {___sendRequest.Routing.ServiceId.Value}.{___sendRequest.Routing.MethodId.Value} not implemented");
//    }

//    protected override IAsyncEnumerable<byte[]> Send_InvokeRequest_ToServiceAsync(InvokeRequestDto ___invokeRequest, CancellationToken ___ct)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(___invokeRequest.BinaryData);
//        switch (___invokeRequest.Routing.ServiceId.Value)
//        {
//            case "ITestApi":
//                switch (___invokeRequest.Routing.MethodId.Value)
//                {
//                    case "Test2":
//                        return ITestApi_Test2(
//                            ___invokeRequest,
//                            ___ct);
//                    case "Test3":
//                        return ITestApi_Test3(
//                            ___invokeRequest,
//                            ___ct);
//                    case "Test5":
//                        return ITestApi_Test5(
//                            ___invokeRequest,
//                            PrimitivesSpanSerializer.ReadString(___span, ref ___offset),
//                            RegisterRemoteAsyncEnumerableArgument<string>(___invokeRequest.Routing, 1, ITestApi_Test5_1_Deserializer),
//                            RegisterRemoteAsyncEnumerableArgument<string>(___invokeRequest.Routing, 2, ITestApi_Test5_2_Deserializer),
//                            ___ct);
//                    case "Test6":
//                        return ITestApi_Test6(
//                            ___invokeRequest,
//                            PrimitivesSpanSerializer.ReadString(___span, ref ___offset),
//                            RegisterRemoteAsyncEnumerableArgument<string>(___invokeRequest.Routing, 1, ITestApi_Test6_1_Deserializer),
//                            RegisterRemoteAsyncEnumerableArgument<string>(___invokeRequest.Routing, 2, ITestApi_Test6_2_Deserializer),
//                            ___ct);
//                }
//                break;
//        }
//        throw new Exception($"Invoke {___invokeRequest.Routing.ServiceId.Value}.{___invokeRequest.Routing.MethodId.Value} not implemented");
//    }

//    public Task ITestApi_Test1(SendRequestDto ___sendRequest, CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test1({___sendRequest})", ___sendRequest);

//        {
//            var ___task = TestApi.Test1();
//            return ITestApi_Test1_Task(___sendRequest, ___task, ___ct);
//        }
//    }
//    public async Task ITestApi_Test1_Task(SendRequestDto ___sendRequest, Task task, CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test1({___sendRequest})", ___sendRequest);

//        {
//            await task;
//        }
//    }

//    public IAsyncEnumerable<byte[]> ITestApi_Test2(InvokeRequestDto ___invokeRequest, [EnumeratorCancellation] CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test2({___invokeRequest})", ___invokeRequest);

//        {
//            var ___responseTask = TestApi.Test2();
//            return ITestApi_Test2_Enumerator(___invokeRequest, ___responseTask, ___ct);
//        }
//    }
//    public async IAsyncEnumerable<byte[]> ITestApi_Test2_Enumerator(InvokeRequestDto ___invokeRequest, Task<string> ___responseTask, [EnumeratorCancellation] CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test2({___invokeRequest})", ___invokeRequest);

//        {
//            yield return ITestApi_Test2_Serializer(await ___responseTask);
//        }
//    }
//    public byte[] ITestApi_Test2_Serializer(string value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(___Buffer);
//        PrimitivesSpanSerializer.WriteString(ref ___span, ref ___offset, value);
//        return ___span.Slice(0, ___offset).ToArray();
//    }

//    public IAsyncEnumerable<byte[]> ITestApi_Test3(InvokeRequestDto ___invokeRequest, [EnumeratorCancellation] CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test3({___invokeRequest})", ___invokeRequest);

//        {
//            var responses = TestApi.Test3(
//                ___ct);
//            return ITestApi_Test3_Enumerator(___invokeRequest, responses, ___ct);
//        }
//    }
//    public async IAsyncEnumerable<byte[]> ITestApi_Test3_Enumerator(InvokeRequestDto ___invokeRequest, IAsyncEnumerable<string> ___responseList, [EnumeratorCancellation] CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test3_Enumerator({___invokeRequest}, {___responseList})",
//                ___invokeRequest,
//                ___responseList);

//        {
//            await foreach (var response in ___responseList)
//            {
//                yield return ITestApi_Test3_Serializer(response);
//            }
//        }
//    }
//    public byte[] ITestApi_Test3_Serializer(string value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(___Buffer);
//        PrimitivesSpanSerializer.WriteString(ref ___span, ref ___offset, value);
//        return ___span.Slice(0, ___offset).ToArray();
//    }

//    public Task ITestApi_Test4(SendRequestDto ___sendRequest, string name, IAsyncEnumerable<string> test, IAsyncEnumerable<string> test2, CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test4({___sendRequest})", ___sendRequest);

//        try
//        {
//            var ___task = TestApi.Test4(name, test, test2);
//            return ITestApi_Test4_Task(___sendRequest, ___task, ___ct);
//        }
//        catch
//        {
//            UnRegisterRemoteAsyncEnumerableArguments(___sendRequest.Routing);
//            throw;
//        }
//    }
//    public async Task ITestApi_Test4_Task(SendRequestDto ___sendRequest, Task task, CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test4({___sendRequest})", ___sendRequest);

//        try
//        {
//            await task;
//        }
//        finally
//        {
//            UnRegisterRemoteAsyncEnumerableArguments(___sendRequest.Routing);
//        }
//    }
//    public string ITestApi_Test4_1_Deserializer(byte[] value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(value);
//        return PrimitivesSpanSerializer.ReadString(___span, ref ___offset);
//    }
//    public string ITestApi_Test4_2_Deserializer(byte[] value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(value);
//        return PrimitivesSpanSerializer.ReadString(___span, ref ___offset);
//    }

//    public IAsyncEnumerable<byte[]> ITestApi_Test5(InvokeRequestDto ___invokeRequest, string name, IAsyncEnumerable<string> test, IAsyncEnumerable<string> test2, [EnumeratorCancellation] CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test5({___invokeRequest})", ___invokeRequest);

//        try
//        {
//            var ___responseTask = TestApi.Test5(
//                name,
//                test,
//                test2);
//            return ITestApi_Test5_Enumerator(___invokeRequest, ___responseTask, ___ct);
//        }
//        catch
//        {
//            UnRegisterRemoteAsyncEnumerableArguments(___invokeRequest.Routing);
//            throw;
//        }
//    }
//    public async IAsyncEnumerable<byte[]> ITestApi_Test5_Enumerator(InvokeRequestDto ___invokeRequest, Task<string> ___responseTask, [EnumeratorCancellation] CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test5({___invokeRequest})", ___invokeRequest);

//        try
//        {
//            yield return ITestApi_Test5_Serializer(await ___responseTask);
//        }
//        finally
//        {
//            UnRegisterRemoteAsyncEnumerableArguments(___invokeRequest.Routing);
//        }
//    }
//    public byte[] ITestApi_Test5_Serializer(string value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(___Buffer);
//        PrimitivesSpanSerializer.WriteString(ref ___span, ref ___offset, value);
//        return ___span.Slice(0, ___offset).ToArray();
//    }
//    public string ITestApi_Test5_1_Deserializer(byte[] value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(value);
//        return PrimitivesSpanSerializer.ReadString(___span, ref ___offset);
//    }
//    public string ITestApi_Test5_2_Deserializer(byte[] value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(value);
//        return PrimitivesSpanSerializer.ReadString(___span, ref ___offset);
//    }

//    public IAsyncEnumerable<byte[]> ITestApi_Test6(InvokeRequestDto ___invokeRequest, string name, IAsyncEnumerable<string> test, IAsyncEnumerable<string> test2, [EnumeratorCancellation] CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test6({___invokeRequest})", ___invokeRequest);

//        try
//        {
//            var responses = TestApi.Test6(
//                name,
//                test,
//                test2,
//                ___ct);
//            return ITestApi_Test6_Enumerator(___invokeRequest, responses, ___ct);
//        }
//        catch
//        {
//            UnRegisterRemoteAsyncEnumerableArguments(___invokeRequest.Routing);
//            throw;
//        }
//    }
//    public async IAsyncEnumerable<byte[]> ITestApi_Test6_Enumerator(InvokeRequestDto ___invokeRequest, IAsyncEnumerable<string> ___responseList, [EnumeratorCancellation] CancellationToken ___ct)
//    {
//        if (___logger.IsEnabled(LogLevel.Trace))
//            ___logger.LogTrace("ITestApi_Test6_Enumerator({___invokeRequest}, {___responseList})",
//                ___invokeRequest,
//                ___responseList);

//        try
//        {
//            await foreach (var response in ___responseList)
//            {
//                yield return ITestApi_Test6_Serializer(response);
//            }
//        }
//        finally
//        {
//            UnRegisterRemoteAsyncEnumerableArguments(___invokeRequest.Routing);
//        }
//    }
//    public byte[] ITestApi_Test6_Serializer(string value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(___Buffer);
//        PrimitivesSpanSerializer.WriteString(ref ___span, ref ___offset, value);
//        return ___span.Slice(0, ___offset).ToArray();
//    }
//    public string ITestApi_Test6_1_Deserializer(byte[] value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(value);
//        return PrimitivesSpanSerializer.ReadString(___span, ref ___offset);
//    }
//    public string ITestApi_Test6_2_Deserializer(byte[] value)
//    {
//        var ___offset = 0;
//        var ___span = new Span<byte>(value);
//        return PrimitivesSpanSerializer.ReadString(___span, ref ___offset);
//    }


//}