<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

	<Target Name="ClearGeneratedFolder" BeforeTargets="BeforeBuild">
		<ItemGroup>
			<FolderToClean Include="$(ProjectDir)Generated\" />
		</ItemGroup>
		<RemoveDir Directories="@(FolderToClean)" />
		<MakeDir Directories="@(FolderToClean)" />
	</Target>
	
	<ItemGroup>
		<Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
	</ItemGroup>

	<ItemGroup>
		<!--<ProjectReference Include="..\gAPI\gAPI.Core\gAPI.Core.csproj" />-->
		<PackageReference Include="gAPI.Core" Version="0.0.2-beta" />
	</ItemGroup>

</Project>
