<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseConsole>true</UseConsole>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="DokanNet" Version="2.3.0.1" />
	  <PackageReference Include="gAPI" Version="0.0.1-alpha" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Domain\IO\Appender\" />
	</ItemGroup>

</Project>
